environment:
  matrix:
    - TARGET: vs2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: '"Visual Studio 15 2017"'

    - TARGET: vs2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: '"Visual Studio 16 2019"'

#branches:
#  except:
#    - more_travis_builds

before_build:
  - cmd: >-

      git submodule update --init --recursive

      cmake -G %GENERATOR% .

      cmake --version

      where fc

build_script:
  - cmd: cmake --build .

test_script:
  - cmd: ctest --verbose -C Debug --output-on-failure
